### ISSUE TITLE
Output data

### ISSUE THREAD

**Issue by skeating** [UCL-Chimera/anonymising_data#4]
All data in CSV form is is CHIMERA share at UCLH
Claire and Steve to review for transfer to DSH
Whole pipeline now scripted

**Comment by skeating** [comment]
The anonymising data pipeline is now set up and running in my home directory of the DSD. I couldn't run it from the Chimera shared folder as it couldn't access the data base from there.

**Comment by skeating** [comment]
Shall I move to the DSH

**Comment by docsteveharris** [comment]
please
